---

    - name: install postgresql
      apt: name={{ item }} state=present
      with_items:
        - postgresql-client-common
        - postgresql
        - postgresql-contrib

    - postgresql_db: name={{ item }}
      with_items: "{{db_list}}"
      sudo: yes
      sudo_user: postgres


    - postgresql_user: db={{ item[0] }} name={{ item[1]}} password={{db_password}} role_attr_flags=CREATEDB,CREATEROLE,CREATEUSER
      with_nested:
        - "{{db_list}}"
        - "{{db_users}}"
      sudo: yes
      sudo_user: postgres

